import type { Message } from '../backend';

interface ConversationData {
  id: string;
  messages: Message[];
}

interface GeneratePDFOptions {
  conversations: ConversationData[];
  startDate?: string;
  endDate?: string;
}

export async function generatePDF({ conversations, startDate, endDate }: GeneratePDFOptions) {
  // Create a new window for printing
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    throw new Error('Failed to open print window. Please allow popups for this site.');
  }

  // Generate HTML content
  const htmlContent = generateHTMLContent(conversations, startDate, endDate);

  // Write content to the new window
  printWindow.document.write(htmlContent);
  printWindow.document.close();

  // Wait for content to load, then trigger print dialog
  printWindow.onload = () => {
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };
}

function generateHTMLContent(
  conversations: ConversationData[],
  startDate?: string,
  endDate?: string
): string {
  const formatTimestamp = (timestamp: bigint) => {
    const date = new Date(Number(timestamp));
    return date.toLocaleString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  let html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Conversation Export</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', sans-serif;
      line-height: 1.6;
      color: #333;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }
    
    @media print {
      body {
        padding: 20px;
      }
      
      .page-break {
        page-break-before: always;
      }
      
      .no-print {
        display: none;
      }
    }
    
    h1 {
      font-size: 28px;
      font-weight: 700;
      margin-bottom: 10px;
      color: #1a1a1a;
      text-align: center;
    }
    
    .subtitle {
      text-align: center;
      color: #666;
      font-size: 14px;
      margin-bottom: 30px;
    }
    
    .date-range {
      text-align: center;
      color: #666;
      font-size: 12px;
      margin-bottom: 40px;
      font-style: italic;
    }
    
    .toc {
      margin-bottom: 40px;
      padding: 20px;
      background: #f5f5f5;
      border-radius: 8px;
    }
    
    .toc h2 {
      font-size: 20px;
      margin-bottom: 15px;
      color: #1a1a1a;
    }
    
    .toc ol {
      margin-left: 20px;
    }
    
    .toc li {
      margin-bottom: 8px;
      color: #333;
    }
    
    .conversation {
      margin-bottom: 50px;
    }
    
    .conversation-header {
      border-bottom: 3px solid #ff6b6b;
      padding-bottom: 10px;
      margin-bottom: 20px;
    }
    
    .conversation-title {
      font-size: 22px;
      font-weight: 600;
      color: #1a1a1a;
      margin-bottom: 5px;
    }
    
    .conversation-meta {
      font-size: 12px;
      color: #666;
    }
    
    .message {
      margin-bottom: 20px;
      padding: 15px;
      background: #f9f9f9;
      border-left: 4px solid #ff6b6b;
      border-radius: 4px;
    }
    
    .message-header {
      display: flex;
      justify-content: space-between;
      align-items: baseline;
      margin-bottom: 8px;
    }
    
    .message-sender {
      font-weight: 600;
      color: #ff6b6b;
      font-size: 14px;
    }
    
    .message-timestamp {
      font-size: 11px;
      color: #999;
    }
    
    .message-text {
      color: #333;
      font-size: 14px;
      white-space: pre-wrap;
      word-wrap: break-word;
    }
    
    .footer {
      margin-top: 60px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      text-align: center;
      font-size: 11px;
      color: #999;
    }
    
    .print-button {
      position: fixed;
      top: 20px;
      right: 20px;
      padding: 12px 24px;
      background: #ff6b6b;
      color: white;
      border: none;
      border-radius: 6px;
      font-size: 14px;
      font-weight: 600;
      cursor: pointer;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
      z-index: 1000;
    }
    
    .print-button:hover {
      background: #ff5252;
    }
  </style>
</head>
<body>
  <button class="print-button no-print" onclick="window.print()">Print / Save as PDF</button>
  
  <h1>Conversation Export</h1>
  <div class="subtitle">Generated by Sansi App Collector</div>
  `;

  if (startDate || endDate) {
    html += `<div class="date-range">Date Range: ${startDate || 'Beginning'} to ${endDate || 'Present'}</div>`;
  }

  // Table of Contents for multiple conversations
  if (conversations.length > 1) {
    html += `
    <div class="toc">
      <h2>Table of Contents</h2>
      <ol>
    `;
    conversations.forEach((conv) => {
      html += `<li>${escapeHtml(conv.id)} (${conv.messages.length} message${conv.messages.length !== 1 ? 's' : ''})</li>`;
    });
    html += `
      </ol>
    </div>
    `;
  }

  // Process each conversation
  conversations.forEach((conv, index) => {
    if (index > 0) {
      html += `<div class="page-break"></div>`;
    }

    const sortedMessages = [...conv.messages].sort((a, b) => Number(a.timestamp) - Number(b.timestamp));

    html += `
    <div class="conversation">
      <div class="conversation-header">
        <h2 class="conversation-title">${escapeHtml(conv.id)}</h2>
        <div class="conversation-meta">${conv.messages.length} message${conv.messages.length !== 1 ? 's' : ''}</div>
      </div>
    `;

    sortedMessages.forEach((msg) => {
      html += `
      <div class="message">
        <div class="message-header">
          <span class="message-sender">${escapeHtml(msg.sender)}</span>
          <span class="message-timestamp">${formatTimestamp(msg.timestamp)}</span>
        </div>
        <div class="message-text">${escapeHtml(msg.text)}</div>
      </div>
      `;
    });

    html += `</div>`;
  });

  html += `
  <div class="footer">
    Generated on ${new Date().toLocaleString()} by Sansi App Collector
  </div>
</body>
</html>
  `;

  return html;
}

function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}
